### ISSUE TITLE
Document is not updated for Extent Report

### ISSUE THREAD

**Issue by prabhat143** [PrecisionTestAutomation/scriptlessautomation-web#18]
The parameter Report_captureScreenshotOnPass in ex which takes a screenshot on the pass as well is not mentioned in the [docs ](https://docs.precisiontestautomation.in/scriptlessautomation/get-started/scriptless-config/reportconfiguration/extentreportconfiguration.properties)

**Comment by PTA-dev** [comment]
Fixed here is the documentation: [link](https://docs.precisiontestautomation.in/scriptlessautomation/get-started/scriptless-config/reportconfiguration/extentreportconfiguration.properties)
